fragments = [
    # Cations
    {'name': 'Ammonium', 'smiles': '[NH4+]', 'fragment_type': 'cation'},
    {'name': 'Phosphonium', 'smiles': '[PH4+]', 'fragment_type': 'cation'},
    {'name': 'Imidazolium', 'smiles': 'C1=CN=C[CNH+]1', 'fragment_type': 'cation'},
    {'name': 'Pyridinium', 'smiles': 'C1=CC=[NH+]C=C1', 'fragment_type': 'cation'},
    {'name': 'Methylimidazolium', 'smiles': 'C[nH+]1cccnc1', 'fragment_type': 'cation'},
    {'name': 'Ethylimidazolium', 'smiles': 'CC[nH+]1cccnc1', 'fragment_type': 'cation'},
    {'name': 'Tetraethylammonium', 'smiles': '[N+](CC)(CC)(CC)CC', 'fragment_type': 'cation'},
    {'name': 'Tetramethylammonium', 'smiles': '[N+](C)(C)(C)C', 'fragment_type': 'cation'},
    {'name': '1-Butyl-3-methylimidazolium', 'smiles': 'CCCC[nH+]1cccnc1C', 'fragment_type': 'cation'},
    {'name': '1-Octyl-3-methylimidazolium', 'smiles': 'CCCCCCCC[nH+]1cccnc1C', 'fragment_type': 'cation'},
    {'name': '1-Ethyl-3-methylpyrrolidinium', 'smiles': 'C[N+]1(CCC)CC1C', 'fragment_type': 'cation'},
    {'name': 'Pyrrolidinium', 'smiles': '[N+]1CCCC1', 'fragment_type': 'cation'},
    {'name': 'Morpholinium', 'smiles': '[N+]1(CCOCC1)', 'fragment_type': 'cation'},
    {'name': 'Diethylmethylammonium', 'smiles': '[N+](C)(CC)(CC)', 'fragment_type': 'cation'},
    {'name': 'Tributylmethylammonium', 'smiles': '[N+](C)(CCCC)(CCCC)(CCCC)', 'fragment_type': 'cation'},
    {'name': 'Tetrabutylphosphonium', 'smiles': '[P+](CCCC)(CCCC)(CCCC)(CCCC)', 'fragment_type': 'cation'},
    {'name': '1-Methylpyridinium', 'smiles': 'C[nH+]1ccccc1', 'fragment_type': 'cation'},
    {'name': '1-Butylpyridinium', 'smiles': 'CCCC[nH+]1ccccc1', 'fragment_type': 'cation'},
    {'name': '1-Propylpyridinium', 'smiles': 'CCC[nH+]1ccccc1', 'fragment_type': 'cation'},
    {'name': '1-Hexylpyridinium', 'smiles': 'CCCCCC[nH+]1ccccc1', 'fragment_type': 'cation'},

    # Anions
    {'name': 'Chloride', 'smiles': '[Cl-]', 'fragment_type': 'anion'},
    {'name': 'Bromide', 'smiles': '[Br-]', 'fragment_type': 'anion'},
    {'name': 'Iodide', 'smiles': '[I-]', 'fragment_type': 'anion'},
    {'name': 'Dicyanamide', 'smiles': '[N-](C#N)C#N', 'fragment_type': 'anion'},
    {'name': 'Trifluoromethanesulfonate', 'smiles': 'C(F)(F)(F)S(=O)(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Acetate', 'smiles': 'CC(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Formate', 'smiles': 'C(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Methanesulfonate', 'smiles': 'CS(=O)(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Tosylate', 'smiles': 'CCc1ccccc1S(=O)(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Trifluoroacetate', 'smiles': 'C(F)(F)F C(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Phosphate', 'smiles': 'O[P](=O)([O-])[O-]', 'fragment_type': 'anion'},
    {'name': 'Bis(trifluoromethanesulfonyl)imide', 'smiles': 'C(F)(F)(F)S(=O)(=O)N(S(=O)(=O)C(F)(F)F)[-]', 'fragment_type': 'anion'},
    {'name': 'Sulfonate', 'smiles': 'S(=O)(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Hydroxide', 'smiles': '[OH-]', 'fragment_type': 'anion'},
    {'name': 'Carbonate', 'smiles': 'O=C([O-])[O-]', 'fragment_type': 'anion'},
    {'name': 'Hydrogen sulfate', 'smiles': 'OS(=O)(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Nitrate', 'smiles': '[N](=O)(=O)[O-]', 'fragment_type': 'anion'},
    {'name': 'Tetrafluoroborate', 'smiles': 'F[B-](F)(F)F', 'fragment_type': 'anion'},
    {'name': 'Bis(fluorosulfonyl)imide', 'smiles': 'F[S](=O)(=O)N(S(=O)(=O)F)[-]', 'fragment_type': 'anion'},
    # "Amino acid" is too general; would depend on which amino acid. Here we leave as placeholder.
    {'name': 'Amino acid', 'smiles': 'NCC([O-])=O', 'fragment_type': 'anion'},  # Example: Glycinate
    {'name': 'Hexafluorophosphate', 'smiles': 'F[P-](F)(F)(F)(F)F', 'fragment_type': 'anion'},
    {'name': 'Thiocyanate', 'smiles': '[SCN-]', 'fragment_type': 'anion'},
    {'name': 'Tricyanomethanide', 'smiles': '[C-](C#N)(C#N)C#N', 'fragment_type': 'anion'},
    {'name': 'Dimethylphosphate', 'smiles': 'CP(=O)(OC)[O-]', 'fragment_type': 'anion'},

    # Alkyl Chains
    {'name': 'Methyl', 'smiles': 'C', 'fragment_type': 'alkyl_chain'},
    {'name': 'Ethyl', 'smiles': 'CC', 'fragment_type': 'alkyl_chain'},
    {'name': 'Propyl', 'smiles': 'CCC', 'fragment_type': 'alkyl_chain'},
    {'name': 'Butyl', 'smiles': 'CCCC', 'fragment_type': 'alkyl_chain'},
    {'name': 'Pentyl', 'smiles': 'CCCCC', 'fragment_type': 'alkyl_chain'},
    {'name': 'Hexyl', 'smiles': 'CCCCCC', 'fragment_type': 'alkyl_chain'},
    {'name': 'Heptyl', 'smiles': 'CCCCCCC', 'fragment_type': 'alkyl_chain'},
    {'name': 'Octyl', 'smiles': 'CCCCCCCC', 'fragment_type': 'alkyl_chain'},
    {'name': 'Nonyl', 'smiles': 'CCCCCCCCC', 'fragment_type': 'alkyl_chain'},
    {'name': 'Decyl', 'smiles': 'CCCCCCCCCC', 'fragment_type': 'alkyl_chain'},
]